language: csharp
mono: none
dotnet: 2.0.0
install:
  - dotnet restore 
script:
  - dotnet build
deploy:
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master