language: csharp
dotnet: 2.0.0
install:
  - dotnet restore 
script:
  - dotnet build
deploy:
  provider: script
  script: dotnet restore && dotnet build && chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master