language: csharp
solution: NuScrap.csproj
script:
  - nuget restore NuScrap.csproj -Verbosity detailed
  - msbuild /p:Configuration=Release NuScrap.csproj
deploy:
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master