language: csharp
dist: trusty
mono: none
dotnet: 1.0.1
install:
  - dotnet restore 
script:
  - dotnet build
deploy:
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master